// ==================== 学校链接数据库 ====================
// 集中管理所有学校的官网和信源链接
const schoolLinks = {
  // 四大
  "深圳中学":"https://www.shenzhong.net/",
  "深圳实验学校（高中部）":"https://szsy.cn/",
  "深圳实验学校":"https://szsy.cn/",
  "深圳外国语学校":"https://www.sfls.net.cn/",
  "深圳高级中学（中心）":"https://www.cn-school.com/",
  "深圳高级中学(中心)":"https://www.cn-school.com/",
  // 十大
  "红岭中学":"https://hlzx.szftedu.cn/",
  "宝安中学":"http://www.bazx.net.cn/",
  "育才中学":"http://yucai.szns.edu.cn/",
  "深大附中":"https://www.sdsyfz.edu.cn/",
  "南外高级中学":"https://nwgz.szns.edu.cn/",
  "深圳科学高中":"https://www.szskgz.com/",
  // 前20
  "北师大南山附中":"https://bsdfz.szns.edu.cn/",
  "南山外国语学校":"https://nswgy.szns.edu.cn/",
  "深圳第二高级中学":"http://www.szsdegz.com/",
  "龙城高级中学":"https://lcgz.szlg.edu.cn/",
  "南科大附中":"https://nkdfz.szns.edu.cn/",
  "翠园中学":"https://cuiyuan.szluohu.edu.cn/",
  "深圳第二实验学校":"http://www.szdesyzx.com/",
  "深理工附中":"https://www.szustafz.com/",
  "龙华高级中学":"https://lhgz.szlhq.edu.cn/",
  "人大附中深圳学校":"https://www.rdfzsz.com/",
  // 二梯队
  "深实验光明高中":"https://szsy.cn/",
  "北大附深":"https://www.pkusz.edu.cn/",
  "深高级东校区":"https://www.cn-school.com/",
  "新安中学（集团）":"http://xazx.baoan.edu.cn/",
  "新安中学(集团)":"http://xazx.baoan.edu.cn/",
  "华中师大龙岗附中":"https://hzsdlgfz.szlg.edu.cn/",
  "深中实验高中":"https://www.szzxgzy.net/",
  "深圳第二外国语学校":"https://szew.szlhq.edu.cn/",
  "深中科技高中":"https://www.szzxgzy.net/",
  "深外龙华":"https://www.sfls.net.cn/",
  "深中数理高中":"https://www.szzxgzy.net/",
  // 三梯队及以下
  "第三高级中学":"http://www.sz3g.com/",
  "光明中学":"https://gmzx.szgm.edu.cn/",
  "坪山高级中学":"https://psgz.szpsq.edu.cn/",
  "松岗中学":"http://sgzx.baoan.edu.cn/",
  "深圳市美术学校":"http://www.szmss.com/",
  "福田中学":"https://ftzx.szftedu.cn/",
  "梅林中学":"https://mlzx.szftedu.cn/",
  "华强职校(普高班)":"http://hqzx.szftedu.cn/",
  "罗湖外语学校":"https://lwxy.szluohu.edu.cn/",
  "罗湖高级中学":"https://lhgz.szluohu.edu.cn/",
  "明德实验学校":"https://www.mdsy.net/",
  "南头中学":"https://ntzx.szns.edu.cn/",
  "盐田高级中学":"https://ytgz.yantian.edu.cn/",
  "西乡中学":"http://xzzx.baoan.edu.cn/",
  "沙井中学":"http://sjzx.baoan.edu.cn/",
  "观澜中学":"https://glzx.szlhq.edu.cn/",
  "布吉中学":"https://bjzx.szlg.edu.cn/",
  "平湖外国语学校":"https://phwgy.szlg.edu.cn/",
  "横岗高级中学":"https://hggz.szlg.edu.cn/",
  "布吉高级中学":"https://bjgz.szlg.edu.cn/",
  "龙岗区外国语学校":"https://lgwgy.szlg.edu.cn/",
  "龙华中学":"https://lhzx.szlhq.edu.cn/",
  "大浪实验学校":"https://dlsy.szlhq.edu.cn/",
  "坪山中学":"https://pszx.szpsq.edu.cn/",
  "光明高级中学":"https://gmgjzx.szgm.edu.cn/",
  "华南师大附中海岸城分校":"https://hsfhac.szns.edu.cn/",
  "致理中学":"https://zlzx.baoan.edu.cn/",
  "平冈中学":"https://pgzx.szlg.edu.cn/",
  "深圳体育实验学校":"https://sztysy.szlg.edu.cn/",
  // 新建高中
  "华南师大坪山实验学校":"https://hsdpssyxx.szpsq.edu.cn/",
  "深圳大学附属教育集团实验高中":"https://www.sdsyfz.edu.cn/",
  "中国科学院深圳理工大学附属实验高中":"https://www.szustafz.com/",
  "东北师大深圳龙华实验学校":"https://dbsd.szlhq.edu.cn/",
  "暨南大学深圳旅游学院附属中学":"https://jnlyfz.szlg.edu.cn/",
  "深圳市厚德书院":"https://www.vanke-meisha.cn/",
  "坪山实验学校高中部":"https://pssyxx.szpsq.edu.cn/",
  // 科创/表演类新增学校
  "深圳市高级中学(中心)":"https://www.cn-school.com/main/zzzs/index.html",
  "深圳市高级中学(东校区)":"https://www.cn-school.com/",
  "深圳市高级中学(创新高中)":"https://www.cn-school.com/",
  "深圳市高级中学(有为高中)":"https://www.cn-school.com/",
  "深圳市高级中学(文博高中)":"https://www.cn-school.com/",
  "深圳实验学校(光明部)":"https://szsy.cn/",
  "深圳实验学校（高中部）":"https://szsy.cn/",
  "深圳实验学校(崇文高中)":"https://szsy.cn/",
  "深圳实验学校(至臻高中)":"https://szsy.cn/",
  "深圳外国语学校(弘知高中)":"https://www.sfls.net.cn/",
  "深圳科学高中(龙岗分校)":"https://www.szskgz.com/",
  "深圳中学科技高中":"https://www.szzxgzy.net/",
  "深圳中学实验高中":"https://www.szzxgzy.net/",
  "深大附属实验中学":"https://www.sdsyfz.edu.cn/",
  "深北理莫附属实验中学":"https://smstd.ru/cn/",
  "南山实验华侨城高级中学":"https://hsfhac.szns.edu.cn/",
  "香港中文大学(深圳)附属明德高级中学":"https://www.mdsy.net/",
  "龙岗区实验高级中学":"https://lgqsygz.szlg.edu.cn/",
  "深圳市龙华科技实验高中":"https://lhkjsy.szlhq.edu.cn/",
  "深圳市龙华外国语高中":"https://lhwgy.szlhq.edu.cn/",
  "深圳市红山中学":"https://hszx.szlhq.edu.cn/",
  "宝安第一外国语学校":"http://bawgy.baoan.edu.cn/",
  "宝安中学(石岩外国语)":"http://www.bazx.net.cn/",
  "宝安中学(龙津中学)":"http://www.bazx.net.cn/",
  "深圳市第二实验(明远高中)":"http://www.szdesyzx.com/",
  "北大附中深圳学校":"https://www.pkusz.edu.cn/",
  "福海中学":"http://fhzx.baoan.edu.cn/",
  "深圳市艺术高中":"https://szysgjzx.szgm.edu.cn/",
  "深圳市富源学校":"https://www.fyedu.net/",
  "深圳市梅沙双语学校":"https://www.meishabilingual.com/",
  "深圳松岗中英文实验学校":"https://www.sgzywsy.com/",
  "深圳菁华中英文实验中学":"http://www.jinghua-edu.cn/",
  "华美外国语学校":"https://www.hmwgyxx.com/",
  "深圳市中新中学":"https://www.zxschool.cn/",
  "深圳市立人高级中学":"https://www.lirengjzx.com/",
  "深圳市育华高级中学":"https://www.yhgjzx.com/",
  "深圳杰仁高级中学":"https://www.jierengjzx.com/",
  "深圳市正德高级中学":"https://www.zdgjzx.com/",
  "深圳市光明书院":"https://www.gmsygjzx.com/",
  "深圳市龙华中英文实验学校":"https://www.lhzywsy.com/",
  "深圳市展华实验学校":"https://www.zhsy.net/",
  "深圳市鹏达高级中学":"https://www.pdgjzx.com/",
  "深圳市德琳学校":"https://www.delinschool.com/",
  "深圳市美中学校":"https://www.mzxx.com/",
  "深圳汉开数理高中":"https://www.hankaimath.com/",
  "深圳市福桥高级中学":"https://www.fqgjzx.com/",
  "深圳市滨海高级中学":"https://www.bhgjzx.com/",
  "深圳市中荟高级中学":"https://www.zhgjzx.com/",
  // 默认信源
  "_default":"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/content/post_12297643.html"
};

// 获取学校链接，没有则返回官方录取标准页
function getSchoolUrl(name) {
  return schoolLinks[name] || schoolLinks["_default"];
}

// ==================== 2025年深圳公办高中录取分数线数据(92所) ====================
const scoreData = [
  {rank:1,name:"深圳中学",district:"罗湖区",ac:574,ac_w:570,d:574,d_w:570,tier:"四大"},
  {rank:2,name:"深圳实验学校（高中部）",district:"福田区",ac:570,ac_w:569,d:571,d_w:570,tier:"四大"},
  {rank:3,name:"深圳外国语学校",district:"盐田区",ac:568,ac_w:"-",d:569,d_w:"-",tier:"四大"},
  {rank:4,name:"深圳高级中学（中心）",district:"福田区",ac:568,ac_w:562,d:568,d_w:562,tier:"四大"},
  {rank:5,name:"红岭中学",district:"福田区",ac:565,ac_w:562,d:566,d_w:563,tier:"十大"},
  {rank:6,name:"宝安中学",district:"宝安区",ac:564,ac_w:"-",d:565,d_w:"-",tier:"十大"},
  {rank:7,name:"育才中学",district:"南山区",ac:564,ac_w:561,d:564,d_w:561,tier:"十大"},
  {rank:8,name:"深大附中",district:"南山区",ac:563,ac_w:560,d:563,d_w:560,tier:"十大"},
  {rank:9,name:"南外高级中学",district:"南山区",ac:561,ac_w:"-",d:561,d_w:"-",tier:"十大"},
  {rank:10,name:"深圳科学高中",district:"龙岗区",ac:560,ac_w:"-",d:562,d_w:"-",tier:"十大"},
  {rank:11,name:"北师大南山附中",district:"南山区",ac:561,ac_w:558,d:561,d_w:558,tier:"前20"},
  {rank:12,name:"南山外国语学校",district:"南山区",ac:556,ac_w:551,d:556,d_w:551,tier:"前20"},
  {rank:13,name:"深圳第二高级中学",district:"南山区",ac:556,ac_w:"-",d:557,d_w:"-",tier:"前20"},
  {rank:14,name:"龙城高级中学",district:"龙岗区",ac:555,ac_w:"-",d:556,d_w:"-",tier:"前20"},
  {rank:15,name:"南科大附中",district:"南山区",ac:554,ac_w:"-",d:555,d_w:"-",tier:"前20"},
  {rank:16,name:"翠园中学",district:"罗湖区",ac:553,ac_w:550,d:554,d_w:551,tier:"前20"},
  {rank:17,name:"深圳第二实验学校",district:"罗湖区",ac:553,ac_w:549,d:553,d_w:549,tier:"前20"},
  {rank:18,name:"深理工附中",district:"光明区",ac:553,ac_w:"-",d:554,d_w:"-",tier:"前20"},
  {rank:19,name:"龙华高级中学",district:"龙华区",ac:551,ac_w:"-",d:552,d_w:"-",tier:"前20"},
  {rank:20,name:"人大附中深圳学校",district:"大鹏新区",ac:550,ac_w:"-",d:551,d_w:"-",tier:"前20"},
  // 二梯队
  {rank:21,name:"深实验光明高中",district:"光明区",ac:549,ac_w:"-",d:550,d_w:"-",tier:"二梯队"},
  {rank:22,name:"北大附深",district:"南山区",ac:548,ac_w:"-",d:549,d_w:"-",tier:"二梯队"},
  {rank:23,name:"深高级东校区",district:"坪山区",ac:546,ac_w:"-",d:543,d_w:"-",tier:"二梯队"},
  {rank:24,name:"新安中学（集团）",district:"宝安区",ac:543,ac_w:"-",d:544,d_w:"-",tier:"二梯队"},
  {rank:25,name:"华中师大龙岗附中",district:"龙岗区",ac:543,ac_w:"-",d:544,d_w:"-",tier:"二梯队"},
  {rank:26,name:"深中实验高中",district:"光明区",ac:541,ac_w:"-",d:542,d_w:"-",tier:"二梯队"},
  {rank:27,name:"深圳第二外国语学校",district:"龙华区",ac:540,ac_w:"-",d:541,d_w:"-",tier:"二梯队"},
  {rank:28,name:"深中科技高中",district:"光明区",ac:539,ac_w:"-",d:540,d_w:"-",tier:"二梯队"},
  {rank:29,name:"深外龙华",district:"龙华区",ac:537,ac_w:"-",d:538,d_w:"-",tier:"二梯队"},
  {rank:30,name:"深中数理高中",district:"光明区",ac:536,ac_w:"-",d:537,d_w:"-",tier:"二梯队"},
  // 三梯队
  {rank:31,name:"福田中学",district:"福田区",ac:534,ac_w:530,d:535,d_w:531,tier:"三梯队"},
  {rank:32,name:"明德实验学校",district:"福田区",ac:533,ac_w:529,d:534,d_w:530,tier:"三梯队"},
  {rank:33,name:"南头中学",district:"南山区",ac:532,ac_w:528,d:533,d_w:529,tier:"三梯队"},
  {rank:34,name:"华南师大附中海岸城分校",district:"南山区",ac:531,ac_w:"-",d:532,d_w:"-",tier:"三梯队"},
  {rank:35,name:"盐田高级中学",district:"盐田区",ac:530,ac_w:"-",d:531,d_w:"-",tier:"三梯队"},
  {rank:36,name:"罗湖外语学校",district:"罗湖区",ac:529,ac_w:525,d:530,d_w:526,tier:"三梯队"},
  {rank:37,name:"罗湖高级中学",district:"罗湖区",ac:528,ac_w:"-",d:529,d_w:"-",tier:"三梯队"},
  {rank:38,name:"致理中学",district:"宝安区",ac:527,ac_w:"-",d:528,d_w:"-",tier:"三梯队"},
  {rank:39,name:"西乡中学",district:"宝安区",ac:527,ac_w:"-",d:528,d_w:"-",tier:"三梯队"},
  {rank:40,name:"第三高级中学",district:"龙岗区",ac:525,ac_w:521,d:526,d_w:522,tier:"三梯队"},
  {rank:41,name:"梅林中学",district:"福田区",ac:524,ac_w:520,d:525,d_w:521,tier:"三梯队"},
  {rank:42,name:"光明中学",district:"光明区",ac:523,ac_w:"-",d:524,d_w:"-",tier:"三梯队"},
  {rank:43,name:"光明高级中学",district:"光明区",ac:522,ac_w:"-",d:523,d_w:"-",tier:"三梯队"},
  {rank:44,name:"平冈中学",district:"龙岗区",ac:521,ac_w:"-",d:522,d_w:"-",tier:"三梯队"},
  {rank:45,name:"龙岗区外国语学校",district:"龙岗区",ac:520,ac_w:"-",d:521,d_w:"-",tier:"三梯队"},
  {rank:46,name:"观澜中学",district:"龙华区",ac:519,ac_w:"-",d:520,d_w:"-",tier:"三梯队"},
  {rank:47,name:"布吉中学",district:"龙岗区",ac:518,ac_w:"-",d:519,d_w:"-",tier:"三梯队"},
  // 四梯队
  {rank:48,name:"龙华中学",district:"龙华区",ac:517,ac_w:"-",d:518,d_w:"-",tier:"四梯队"},
  {rank:49,name:"平湖外国语学校",district:"龙岗区",ac:516,ac_w:"-",d:517,d_w:"-",tier:"四梯队"},
  {rank:50,name:"坪山高级中学",district:"坪山区",ac:515,ac_w:"-",d:516,d_w:"-",tier:"四梯队"},
  {rank:51,name:"横岗高级中学",district:"龙岗区",ac:514,ac_w:"-",d:515,d_w:"-",tier:"四梯队"},
  {rank:52,name:"布吉高级中学",district:"龙岗区",ac:513,ac_w:"-",d:514,d_w:"-",tier:"四梯队"},
  {rank:53,name:"沙井中学",district:"宝安区",ac:512,ac_w:"-",d:513,d_w:"-",tier:"四梯队"},
  {rank:54,name:"大浪实验学校",district:"龙华区",ac:511,ac_w:"-",d:512,d_w:"-",tier:"四梯队"},
  {rank:55,name:"坪山中学",district:"坪山区",ac:510,ac_w:"-",d:511,d_w:"-",tier:"四梯队"},
  {rank:56,name:"华南师大坪山实验学校",district:"坪山区",ac:509,ac_w:"-",d:510,d_w:"-",tier:"四梯队"},
  {rank:57,name:"东北师大深圳龙华实验学校",district:"龙华区",ac:508,ac_w:"-",d:509,d_w:"-",tier:"四梯队"},
  {rank:58,name:"深圳大学附属教育集团实验高中",district:"龙岗区",ac:507,ac_w:"-",d:508,d_w:"-",tier:"四梯队"},
  {rank:59,name:"中国科学院深圳理工大学附属实验高中",district:"光明区",ac:506,ac_w:"-",d:507,d_w:"-",tier:"四梯队"},
  {rank:60,name:"暨南大学深圳旅游学院附属中学",district:"龙岗区",ac:505,ac_w:"-",d:506,d_w:"-",tier:"四梯队"},
  {rank:61,name:"松岗中学",district:"宝安区",ac:501,ac_w:"-",d:502,d_w:"-",tier:"四梯队"},
  {rank:62,name:"深圳体育实验学校",district:"龙岗区",ac:498,ac_w:"-",d:499,d_w:"-",tier:"四梯队"},
  {rank:63,name:"坪山实验学校高中部",district:"坪山区",ac:496,ac_w:"-",d:497,d_w:"-",tier:"四梯队"},
  // 特色校
  {rank:64,name:"深圳市美术学校",district:"罗湖区",ac:459,ac_w:"-",d:492,d_w:"-",tier:"艺术特色"},
  {rank:65,name:"华强职校(普高班)",district:"福田区",ac:459,ac_w:444,d:470,d_w:"-",tier:"特色校"}
];

// ==================== 民办高中数据(47所) ====================
const privateSchoolData = [
  {rank:1,name:"富源学校",district:"宝安区",ac:415,d:415,fee:"3.8万/学期",tier:"民办头部",url:"https://www.fyschool.com/"},
  {rank:2,name:"中澳实验学校",district:"宝安区",ac:400,d:400,fee:"3.5万/学期",tier:"民办头部",url:"http://www.szza.edu.cn/"},
  {rank:3,name:"金华中学",district:"龙华区",ac:377,d:377,fee:"2.8万/学期",tier:"民办中上"},
  {rank:4,name:"桃源居中澳实验学校",district:"宝安区",ac:375,d:375,fee:"3.2万/学期",tier:"民办中上"},
  {rank:5,name:"耀华实验学校",district:"福田区",ac:370,d:370,fee:"3.5万/学期",tier:"民办中上",url:"http://www.szyhfz.com/"},
  {rank:6,name:"翻身实验学校",district:"宝安区",ac:368,d:368,fee:"2.6万/学期",tier:"民办中等"},
  {rank:7,name:"石岩公学",district:"宝安区",ac:365,d:365,fee:"2.5万/学期",tier:"民办中等"},
  {rank:8,name:"承翰学校",district:"龙岗区",ac:363,d:363,fee:"2.8万/学期",tier:"民办中等"},
  {rank:9,name:"东方英文书院",district:"宝安区",ac:360,d:360,fee:"2.6万/学期",tier:"民办中等"},
  {rank:10,name:"北大新世纪学校",district:"南山区",ac:358,d:358,fee:"3.6万/学期",tier:"民办中等"},
  {rank:11,name:"崛起实验学校",district:"宝安区",ac:356,d:356,fee:"2.5万/学期",tier:"民办中等"},
  {rank:12,name:"明珠学校",district:"罗湖区",ac:355,d:355,fee:"2.3万/学期",tier:"民办中等"},
  {rank:13,name:"皇御苑学校",district:"福田区",ac:353,d:353,fee:"2.6万/学期",tier:"民办中等"},
  {rank:14,name:"奥斯翰外语学校",district:"罗湖区",ac:351,d:351,fee:"3.2万/学期",tier:"民办中等"},
  {rank:15,name:"宝安区明德外语实验学校",district:"宝安区",ac:350,d:350,fee:"2.5万/学期",tier:"民办中等"},
  {rank:16,name:"龙岗区科城实验学校",district:"龙岗区",ac:349,d:349,fee:"2.8万/学期",tier:"民办中等"},
  {rank:17,name:"华胜实验学校",district:"光明区",ac:348,d:348,fee:"2.3万/学期",tier:"民办中下"},
  {rank:18,name:"龙华区诺德安达双语学校",district:"龙华区",ac:347,d:347,fee:"6.8万/学期",tier:"民办中下"},
  {rank:19,name:"展华实验学校",district:"龙华区",ac:346,d:346,fee:"2.4万/学期",tier:"民办中下"},
  {rank:20,name:"建文外国语学校",district:"宝安区",ac:345,d:345,fee:"3.0万/学期",tier:"民办中下"},
  {rank:21,name:"东升学校",district:"龙岗区",ac:344,d:344,fee:"2.2万/学期",tier:"民办中下"},
  {rank:22,name:"南山为明学校",district:"南山区",ac:343,d:343,fee:"3.5万/学期",tier:"民办中下"},
  {rank:23,name:"育新学校",district:"宝安区",ac:342,d:342,fee:"2.0万/学期",tier:"民办中下"},
  {rank:24,name:"龙岗区华中师大附属龙园学校",district:"龙岗区",ac:341,d:341,fee:"2.8万/学期",tier:"民办中下"},
  {rank:25,name:"光明区公明中英文学校",district:"光明区",ac:340,d:340,fee:"2.0万/学期",tier:"民办中下"},
  {rank:26,name:"福田区方方乐趣学校",district:"福田区",ac:339,d:339,fee:"3.5万/学期",tier:"民办中下"},
  {rank:27,name:"宝安区康桥书院",district:"宝安区",ac:338,d:338,fee:"2.8万/学期",tier:"民办中下"},
  {rank:28,name:"龙翔学校",district:"龙岗区",ac:337,d:337,fee:"2.0万/学期",tier:"民办中下"},
  {rank:29,name:"华美外国语学校",district:"罗湖区",ac:336,d:336,fee:"4.2万/学期",tier:"民办中下"},
  {rank:30,name:"宝安区华一实验学校",district:"宝安区",ac:335,d:335,fee:"2.2万/学期",tier:"民办基础"},
  {rank:31,name:"深圳市携创高级技工学校(普高班)",district:"龙岗区",ac:334,d:334,fee:"2.5万/学期",tier:"民办基础"},
  {rank:32,name:"北斗中学",district:"宝安区",ac:333,d:333,fee:"2.8万/学期",tier:"民办基础"},
  {rank:33,name:"宝安区中心明德外语实验学校",district:"宝安区",ac:332,d:332,fee:"2.5万/学期",tier:"民办基础"},
  {rank:34,name:"坪山区博明学校",district:"坪山区",ac:331,d:331,fee:"2.0万/学期",tier:"民办基础"},
  {rank:35,name:"龙岗区德龙学校",district:"龙岗区",ac:330,d:330,fee:"2.0万/学期",tier:"民办基础"},
  {rank:36,name:"龙岗区立人高级中学",district:"龙岗区",ac:329,d:329,fee:"3.0万/学期",tier:"民办基础"},
  {rank:37,name:"宝安区和平中英文实验学校",district:"宝安区",ac:328,d:328,fee:"2.2万/学期",tier:"民办基础"},
  {rank:38,name:"万科梅沙书院",district:"盐田区",ac:327,d:327,fee:"9.5万/学期",tier:"国际方向"},
  {rank:39,name:"深圳实验承翰学校",district:"龙岗区",ac:327,d:327,fee:"3.2万/学期",tier:"民办基础"},
  {rank:40,name:"宝安区松岗华一实验学校",district:"宝安区",ac:326,d:326,fee:"2.0万/学期",tier:"民办基础"},
  {rank:41,name:"龙岗区国际预科学院",district:"龙岗区",ac:326,d:326,fee:"8.5万/学期",tier:"国际方向"},
  {rank:42,name:"坪山区兴旺学校",district:"坪山区",ac:325,d:325,fee:"2.0万/学期",tier:"民办基础"},
  {rank:43,name:"光明区培英文武实验学校",district:"光明区",ac:325,d:325,fee:"2.0万/学期",tier:"民办基础"},
  {rank:44,name:"宝安区明星学校",district:"宝安区",ac:325,d:325,fee:"2.0万/学期",tier:"民办基础"},
  {rank:45,name:"龙岗区龙城培根书院",district:"龙岗区",ac:325,d:325,fee:"3.5万/学期",tier:"民办基础"},
  {rank:46,name:"龙华区新华中英文学校",district:"龙华区",ac:325,d:325,fee:"2.0万/学期",tier:"民办基础"},
  {rank:47,name:"罗湖区华美外国语学校",district:"罗湖区",ac:325,d:325,fee:"4.2万/学期",tier:"民办基础"}
];

// ==================== 中职/技工学校数据 ====================
const vocationalData = [
  // 第一批试点专业(高分段)
  {name:"深圳市第一职业技术学校",short:"深圳一职",batch:"第一批",topScore:491,lowScore:460,hotMajors:["工业机器人技术应用(491)","药品食品检验(490)","计算机应用(489)","制药技术应用(488)","环境治理技术(482)"],url:"http://www.szyzx.net/",district:"福田区",type:"国家级重点"},
  {name:"深圳市第二职业技术学校",short:"深圳二职",batch:"第一批",topScore:489,lowScore:450,hotMajors:["计算机应用·三二分段(489)","新能源汽车(488)","人工智能技术(484)","网络信息安全(483)","工业设计(475)"],url:"http://www.szez.net/",district:"光明区",type:"国家级重点"},
  {name:"深圳市第三职业技术学校",short:"深圳三职",batch:"第一批",topScore:481,lowScore:440,hotMajors:["计算机网络技术(481)","动漫与游戏制作(472)","物联网技术(468)","汽车运用与维修(455)"],url:"http://www.szvtc.cn/",district:"坪山区",type:"省级重点"},
  {name:"深圳市龙岗职业技术学校",short:"龙岗职校",batch:"第一批",topScore:470,lowScore:430,hotMajors:["计算机应用(470)","电子商务(462)","数控技术(450)","汽车维修(440)"],url:"http://lgzx.szlg.edu.cn/",district:"龙岗区",type:"国家级重点"},
  {name:"深圳市宝安职业技术学校",short:"宝安职校",batch:"第一批",topScore:465,lowScore:425,hotMajors:["计算机应用(465)","电气自动化(455)","数控技术(448)","汽车维修(435)"],url:"http://szbazx.net/",district:"宝安区",type:"国家级重点"},
  {name:"深圳市龙华职业技术学校",short:"龙华职校",batch:"第一批",topScore:460,lowScore:420,hotMajors:["计算机应用(460)","电子商务(450)","工业机器人(442)"],url:"https://lhzx.szlhq.edu.cn/",district:"龙华区",type:"省级重点"},
  {name:"深圳市奋达职业技术学校",short:"奋达职校",batch:"第一批",topScore:458,lowScore:410,hotMajors:["计算机应用(458)","电子技术(445)","艺术设计(430)"],url:"http://www.szfdxy.com/",district:"宝安区",type:"省级重点"},
  {name:"深圳市开放职业技术学校",short:"开放职校",batch:"第二批",topScore:440,lowScore:380,hotMajors:["计算机应用(440)","电子商务(420)","会计(400)"],url:"http://www.szcj.net/",district:"罗湖区",type:"市级中职"},
  {name:"深圳市盐港中学(职高部)",short:"盐港中学",batch:"第二批",topScore:430,lowScore:370,hotMajors:["电子技术(430)","计算机(415)","旅游(390)"],url:"https://ygzx.yantian.edu.cn/",district:"盐田区",type:"市级中职"},
  // 技工学校
  {name:"深圳技师学院",short:"深圳技师",batch:"第一批",topScore:478,lowScore:420,hotMajors:["新能源汽车(478)","智能制造(470)","物联网(462)","人工智能(456)"],url:"https://www.ssti.net.cn/",district:"龙岗区",type:"技师学院"},
  {name:"深圳市技工学校",short:"深圳技校",batch:"第一批",topScore:455,lowScore:400,hotMajors:["电气自动化(455)","数控技术(440)","电子商务(425)"],url:"https://www.sztec.net/",district:"福田区",type:"高级技工"},
  {name:"深圳市携创高级技工学校",short:"携创技工",batch:"第二批",topScore:420,lowScore:350,hotMajors:["计算机应用(420)","电子商务(400)","烹饪(370)"],url:"https://www.szxcjx.com/",district:"龙岗区",type:"高级技工"},
  {name:"深圳市深德技工学校",short:"深德技工",batch:"第二批",topScore:380,lowScore:300,hotMajors:["汽车维修(380)","电子商务(350)","美容美发(310)"],url:"http://www.szsdvs.com/",district:"光明区",type:"技工学校"},
  {name:"深圳市宝山技工学校",short:"宝山技工",batch:"第二批",topScore:370,lowScore:290,hotMajors:["计算机(370)","电商(340)","幼教(310)"],url:"http://www.szbsjg.com/",district:"坪山区",type:"技工学校"},
  {name:"深圳市科迪技工学校",short:"科迪技工",batch:"第二批",topScore:360,lowScore:280,hotMajors:["计算机(360)","电商(330)","会计(300)"],district:"龙华区",type:"技工学校"},
  {name:"深圳市新南方技工学校",short:"新南方",batch:"第二批",topScore:350,lowScore:265,hotMajors:["电子商务(350)","计算机(320)","烹饪(280)"],district:"宝安区",type:"技工学校"}
];

// ==================== 科创类自主招生学校（官方完整数据） ====================
// 数据来源：深圳市教育局《2025年公办/民办普通高中学校自主招生计划》
const scienceData = [
  // ===== 公办·四大名校 =====
  {name:"深圳中学",type:"公办",dir:"信息与人工智能/数学英才/强基",quota:"14人(信息AI)",total:400,ctrl:510,score:574,tier:"四大",url:"https://www.shenzhong.net/textnewslist_25/16849.html"},
  {name:"深圳实验学校（高中部）",type:"公办",dir:"信息技术",quota:"4人(信息技术)",total:95,ctrl:511,score:570,tier:"四大",url:"https://szsy.cn/"},
  {name:"深圳市高级中学(中心)",type:"公办",dir:"信息",quota:"10人(信息)",total:180,ctrl:509,score:568,tier:"四大",url:"https://www.cn-school.com/main/zzzs/index.html"},
  // ===== 公办·十大/前20 =====
  {name:"深圳科学高中",type:"公办",dir:"科创(人工智能)/数学",quota:"30人(AI)+30数学+50拔尖",total:110,ctrl:500,score:560,tier:"十大",url:"https://www.szskgz.com/"},
  {name:"宝安中学",type:"公办",dir:"信息技术/发明创意/机器人与航空航天",quota:"信息2+发明2+机器人航天3",total:80,ctrl:520,score:564,tier:"十大",url:"http://www.bazx.net.cn/"},
  {name:"南科大附中",type:"公办",dir:"信息技术",quota:"5人(信息技术)",total:70,ctrl:530,score:554,tier:"前20",url:"https://nkdfz.szns.edu.cn/"},
  {name:"翠园中学",type:"公办",dir:"科技发明与人工智能",quota:"9人(科创AI)",total:39,ctrl:510,score:553,tier:"前20",url:"https://cuiyuan.szluohu.edu.cn/"},
  {name:"深大附中",type:"公办",dir:"信息技术",quota:"10人(信息技术)",total:60,ctrl:503,score:563,tier:"十大",url:"https://www.sdsyfz.edu.cn/"},
  {name:"盐田高级中学",type:"公办",dir:"生命科学与信息科技创新",quota:"9人(生命科学+信息科技)",total:17,ctrl:508,score:556,tier:"前20",url:"https://ytgz.yantian.edu.cn/"},
  // ===== 公办·二梯队 =====
  {name:"深圳第二高级中学",type:"公办",dir:"AI及创造发明",quota:"10人(AI+创造发明)",total:50,ctrl:495,score:556,tier:"前20",url:"http://www.szsdegz.com/"},
  {name:"龙华高级中学",type:"公办",dir:"科创(三航科学技术)",quota:"30人(三航科技)",total:60,ctrl:495,score:551,tier:"前20",url:"https://lhgz.szlhq.edu.cn/"},
  {name:"深大附属实验中学",type:"公办",dir:"信息技术(人工智能)",quota:"4人(AI)",total:45,ctrl:495,score:550,tier:"前20",url:"https://www.sdsyfz.edu.cn/"},
  {name:"南山实验华侨城高级中学",type:"公办",dir:"科创(科技创新创意制作)",quota:"30人(科创制作)",total:40,ctrl:490,score:548,tier:"二梯队",url:"https://hsfhac.szns.edu.cn/"},
  {name:"深圳实验学校(光明部)",type:"公办",dir:"信息技术/AI/科创发明/智能机器人",quota:"信息15+AI6+发明6+机器人3",total:51,ctrl:489,score:545,tier:"二梯队",url:"https://szsy.cn/"},
  {name:"香港中文大学(深圳)附属明德高级中学",type:"公办",dir:"科创(人工智能)/科创(机器人)",quota:"AI10+机器人10",total:40,ctrl:500,score:543,tier:"二梯队",url:"https://www.mdsy.net/"},
  {name:"深圳市高级中学(东校区)",type:"公办",dir:"数学/物理",quota:"数学13+物理8",total:41,ctrl:485,score:542,tier:"二梯队",url:"https://www.cn-school.com/"},
  {name:"深圳科学高中(龙岗分校)",type:"公办",dir:"科创(机器人编程与智能设计)",quota:"16人(机器人编程)",total:46,ctrl:484,score:540,tier:"二梯队",url:"https://www.szskgz.com/"},
  {name:"华中师大龙岗附中",type:"公办",dir:"数学/物理",quota:"数学30+物理20",total:60,ctrl:484,score:538,tier:"二梯队",url:"https://hzsdlgfz.szlg.edu.cn/"},
  {name:"深北理莫附属实验中学",type:"公办",dir:"信息技术",quota:"20人(信息技术)",total:80,ctrl:481,score:536,tier:"二梯队",url:"https://smstd.ru/cn/"},
  {name:"深圳市红山中学",type:"公办",dir:"科技",quota:"30人(科技)",total:30,ctrl:476,score:535,tier:"二梯队",url:"https://hszx.szlhq.edu.cn/"},
  {name:"深理工附中",type:"公办",dir:"科创(集成电路与算法设计)",quota:"7人(芯片算法)",total:57,ctrl:476,score:553,tier:"前20",url:"https://www.szustafz.com/"},
  {name:"松岗中学",type:"公办",dir:"智能机器人创意设计与编程",quota:"5人(机器人编程)",total:10,ctrl:475,score:501,tier:"三梯队",url:"http://sgzx.baoan.edu.cn/"},
  {name:"宝安第一外国语学校",type:"公办",dir:"科创(Arduino机器人编程)",quota:"6人(机器人编程)",total:36,ctrl:474,score:530,tier:"二梯队",url:"http://bawgy.baoan.edu.cn/"},
  {name:"深圳市高级中学(创新高中)",type:"公办",dir:"信息",quota:"3人(信息)",total:45,ctrl:473,score:530,tier:"二梯队",url:"https://www.cn-school.com/"},
  {name:"深圳第二外国语学校",type:"公办",dir:"航空航天/科创(机器人)",quota:"航天22+机器人20",total:62,ctrl:471,score:540,tier:"二梯队",url:"https://szew.szlhq.edu.cn/"},
  {name:"龙岗区实验高级中学",type:"公办",dir:"科创(人工智能与智能机器人)",quota:"20人(AI+机器人)",total:24,ctrl:471,score:528,tier:"二梯队",url:"https://lgqsygz.szlg.edu.cn/"},
  {name:"福田中学",type:"公办",dir:"科创(智能机器人创意设计与编程)",quota:"17人(机器人编程)",total:47,ctrl:471,score:532,tier:"二梯队",url:"https://ftzx.szftedu.cn/"},
  {name:"光明区高级中学",type:"公办",dir:"科创(科技发明与机器人)",quota:"6人(科技发明+机器人)",total:30,ctrl:470,score:523,tier:"三梯队",url:"https://gmgjzx.szgm.edu.cn/"},
  {name:"罗湖高级中学",type:"公办",dir:"信息技术",quota:"12人(信息技术)",total:12,ctrl:459,score:510,tier:"三梯队",url:"https://lhgz.szluohu.edu.cn/"},
  // ===== 公办·三梯队/新建校 =====
  {name:"新安中学(燕川中学)",type:"公办",dir:"科创(人工智能)/科创(航天科技)",quota:"AI6+航天7",total:13,ctrl:454,score:520,tier:"三梯队",url:"http://xazx.baoan.edu.cn/"},
  {name:"深圳市高级中学(有为高中)",type:"公办",dir:"科创(智能机器人与编程)",quota:"5人(机器人编程)",total:30,ctrl:453,score:518,tier:"三梯队",url:"https://www.cn-school.com/"},
  {name:"深圳外国语学校(弘知高中)",type:"公办",dir:"科创(创意制造与编程)",quota:"9人(创意编程)",total:59,ctrl:451,score:516,tier:"三梯队",url:"https://www.sfls.net.cn/"},
  {name:"深圳实验学校(崇文高中)",type:"公办",dir:"科技",quota:"20人(科技)",total:50,ctrl:446,score:514,tier:"三梯队",url:"https://szsy.cn/"},
  {name:"北大附中深圳学校",type:"公办",dir:"科学教育",quota:"20人(科学教育)",total:30,ctrl:445,score:512,tier:"三梯队",url:"https://www.pkusz.edu.cn/"},
  {name:"西乡中学",type:"公办",dir:"科创(机器人创意设计与编程)",quota:"12人(机器人编程)",total:12,ctrl:444,score:508,tier:"三梯队",url:"http://xzzx.baoan.edu.cn/"},
  {name:"深圳市龙华科技实验高中",type:"公办",dir:"编程/科创(人工智能与机器人)",quota:"编程20+AI机器人15",total:55,ctrl:440,score:505,tier:"三梯队",url:"https://lhkjsy.szlhq.edu.cn/"},
  {name:"福海中学",type:"公办",dir:"科创(创客/无人机/机器人)",quota:"创客4+无人机2+机器人2",total:13,ctrl:436,score:500,tier:"三梯队",url:"http://fhzx.baoan.edu.cn/"},
  {name:"深圳市龙华外国语高中",type:"公办",dir:"科创(智能机器人)",quota:"5人(智能机器人)",total:13,ctrl:434,score:498,tier:"三梯队",url:"https://lhwgy.szlhq.edu.cn/"},
  {name:"致理中学",type:"公办",dir:"AI/智能机器人/科创发明/航空航天/芯片科技",quota:"AI5+机器人10+发明5+航天5+芯片5",total:40,ctrl:427,score:495,tier:"三梯队",url:"https://zlzx.baoan.edu.cn/"},
  {name:"深圳实验学校(至臻高中)",type:"公办",dir:"信息技术",quota:"15人(信息技术)",total:15,ctrl:426,score:490,tier:"三梯队",url:"https://szsy.cn/"},
  {name:"深圳中学科技高中",type:"公办",dir:"科创(AI软硬件开发)/天文",quota:"科创AI30+天文30",total:180,ctrl:418,score:539,tier:"二梯队",url:"https://www.szzxgzy.net/"},
  {name:"深圳中学实验高中",type:"公办",dir:"信息",quota:"30人(信息)",total:150,ctrl:420,score:530,tier:"二梯队",url:"https://www.szzxgzy.net/"},
  {name:"深圳市第二实验(明远高中)",type:"公办",dir:"信息技术",quota:"5人(信息技术)",total:5,ctrl:418,score:488,tier:"三梯队",url:"http://www.szdesyzx.com/"},
  {name:"宝安中学(石岩外国语)",type:"公办",dir:"科创(人工智能)",quota:"5人(AI)",total:8,ctrl:405,score:480,tier:"三梯队",url:"http://www.bazx.net.cn/"},
  {name:"宝安中学(龙津中学)",type:"公办",dir:"科创(水下机器人与设计编程)",quota:"10人(水下机器人编程)",total:20,ctrl:468,score:518,tier:"三梯队",url:"http://www.bazx.net.cn/"},
  // ===== 民办学校 =====
  {name:"深圳市富源学校",type:"民办",dir:"信息技术",quota:"10人(信息技术)",total:30,ctrl:560,score:0,tier:"民办",url:"https://www.fyedu.net/"},
  {name:"深圳市梅沙双语学校",type:"民办",dir:"理工科技(物理)",quota:"15人(物理)",total:19,ctrl:403,score:0,tier:"民办",url:"https://www.meishabilingual.com/"},
  {name:"深圳松岗中英文实验学校",type:"民办",dir:"理工科技(物理)",quota:"10人(物理)",total:20,ctrl:293,score:0,tier:"民办",url:"https://www.sgzywsy.com/"}
];

// ==================== 主持表演类自主招生学校（官方完整数据） ====================
// 数据来源：深圳市教育局《2025年公办/民办普通高中学校自主招生计划》
const artData = [
  // ===== 公办学校 =====
  {name:"深圳外国语学校",type:"公办",project:"戏剧表演",detail:"音乐剧",quota:"12人",ctrl:424,score:568,district:"福田区",note:"四大名校，戏剧表演王牌",url:"https://www.sfls.net.cn/"},
  {name:"深圳市高级中学(中心)",type:"公办",project:"戏剧表演",detail:"戏剧表演",quota:"2人",ctrl:424,score:568,district:"福田区",note:"四大名校，精英选拔",url:"https://www.cn-school.com/main/zzzs/index.html"},
  {name:"深圳市高级中学(东校区)",type:"公办",project:"戏剧表演",detail:"戏剧表演",quota:"8人",ctrl:404,score:542,district:"坪山区",note:"名校分校，名额充足",url:"https://www.cn-school.com/"},
  {name:"深圳第二高级中学",type:"公办",project:"戏剧表演",detail:"影视戏剧表演",quota:"4人",ctrl:413,score:556,district:"南山区",note:"艺术教育特色，影视方向",url:"http://www.szsdegz.com/"},
  {name:"深圳市高级中学(创新高中)",type:"公办",project:"戏剧表演",detail:"偶剧表演",quota:"5人",ctrl:394,score:530,district:"龙岗区",note:"独特偶剧方向，新赛道",url:"https://www.cn-school.com/"},
  {name:"深圳市高级中学(文博高中)",type:"公办",project:"播音与主持",detail:"播音主持",quota:"2人",ctrl:380,score:510,district:"龙华区",note:"新建校区，竞争相对小",url:"https://www.cn-school.com/"},
  {name:"深圳市美术学校",type:"公办",project:"戏剧表演",detail:"戏剧表演",quota:"6人",ctrl:360,score:459,district:"罗湖区",note:"唯一公办艺术高中，控制线极低",url:"http://www.szmss.com/"},
  {name:"深圳市艺术高中",type:"公办",project:"戏剧表演",detail:"表演·播音主持·导演·服装表演",quota:"14人",ctrl:338,score:450,district:"光明区",note:"全市控制线最低，名额最多！",url:"https://szysgjzx.szgm.edu.cn/"},
  {name:"横岗高级中学",type:"公办",project:"播音与主持",detail:"播音与主持",quota:"7人",ctrl:344,score:480,district:"龙岗区",note:"控制线低，名额充足",url:"https://hggz.szlg.edu.cn/"},
  {name:"平冈中学",type:"公办",project:"播音与主持",detail:"播音与主持",quota:"2人",ctrl:378,score:495,district:"龙岗区",note:"龙岗老牌高中",url:"https://pgzx.szlg.edu.cn/"},
  // ===== 民办学校 =====
  {name:"深圳菁华中英文实验中学",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"30人",ctrl:245,score:0,district:"罗湖区",note:"民办名额最多，低门槛",url:"http://www.jinghua-edu.cn/"},
  {name:"深圳市中新中学",type:"民办",project:"播音与主持·戏剧表演",detail:"播音15+戏剧15",quota:"30人",ctrl:280,score:0,district:"龙岗区",note:"双项目招生，名额充足",url:"https://www.zxschool.cn/"},
  {name:"深圳市立人高级中学",type:"民办",project:"播音与主持·戏剧表演",detail:"播音10+戏剧10",quota:"20人",ctrl:250,score:0,district:"龙岗区",note:"低门槛双项目，保底选择",url:"https://www.lirengjzx.com/"},
  {name:"深圳市育华高级中学",type:"民办",project:"播音与主持·戏剧表演",detail:"播音10+戏剧10",quota:"20人",ctrl:250,score:0,district:"龙华区",note:"龙华民办，双项目招生",url:"https://www.yhgjzx.com/"},
  {name:"深圳杰仁高级中学",type:"民办",project:"播音与主持·戏剧表演",detail:"播音10+戏剧8",quota:"18人",ctrl:320,score:0,district:"光明区",note:"光明区民办，名额多",url:"https://www.jierengjzx.com/"},
  {name:"深圳市正德高级中学",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"15人",ctrl:280,score:0,district:"龙华区",note:"低门槛保底",url:"https://www.zdgjzx.com/"},
  {name:"深圳市光明书院",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"15人",ctrl:245,score:0,district:"光明区",note:"最低控制线之一",url:"https://www.gmsygjzx.com/"},
  {name:"华美外国语学校",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:245,score:0,district:"罗湖区",note:"罗湖区民办",url:"https://www.hmwgyxx.com/"},
  {name:"深圳市龙华中英文实验学校",type:"民办",project:"播音与主持·戏剧表演",detail:"播音10+戏剧10",quota:"20人",ctrl:244,score:0,district:"龙华区",note:"全市最低控制线！",url:"https://www.lhzywsy.com/"},
  {name:"深圳市展华实验学校",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:260,score:0,district:"龙华区",note:"民办中等门槛",url:"https://www.zhsy.net/"},
  {name:"深圳市鹏达高级中学",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:260,score:0,district:"龙岗区",note:"龙岗民办",url:"https://www.pdgjzx.com/"},
  {name:"深圳市德琳学校",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:350,score:0,district:"龙岗区",note:"民办较高门槛",url:"https://www.delinschool.com/"},
  {name:"深圳市美中学校",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:306,score:0,district:"龙华区",note:"大规模民办",url:"https://www.mzxx.com/"},
  {name:"深圳汉开数理高中",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:360,score:0,district:"光明区",note:"数理见长也有艺术项目",url:"https://www.hankaimath.com/"},
  {name:"深圳市福桥高级中学",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"10人",ctrl:320,score:0,district:"福田区",note:"福田区民办",url:"https://www.fqgjzx.com/"},
  {name:"深圳市滨海高级中学",type:"民办",project:"播音与主持·戏剧表演",detail:"播音2+戏剧1",quota:"3人",ctrl:300,score:0,district:"宝安区",note:"名额少但门槛低",url:"https://www.bhgjzx.com/"},
  {name:"深圳市中荟高级中学",type:"民办",project:"播音与主持",detail:"播音与主持",quota:"15人",ctrl:245,score:0,district:"宝安区",note:"最低控制线之一",url:"https://www.zhgjzx.com/"}
];

// ==================== 高中简介数据 ====================
const schoolProfiles = [
  // ===== 四大 =====
  {name:"深圳中学",district:"罗湖区",type:"四大",color:"",score:574,
   desc:"广东省首批国家级示范性高中，百年名校。高考重本率长期全市第一，竞赛成绩全省领先。拥有数学英才班、强基班等拔尖培养项目。",
   tags:["百年名校","竞赛强校","清北率极高","科创中心"],
   recruit:"一类360人(理工科技125+强基英才75+拔尖180)\n二类117人(体育39+音乐舞蹈78)"},
  {name:"深圳实验学校",district:"福田区",type:"四大",color:"green",score:570,
   desc:"市教育局直属重点学校，以素质教育闻名。小班化教学，注重全面发展，艺术和科创教育突出。",
   tags:["素质教育标杆","小班教学","科创特色","艺术强校"],
   recruit:"一类~120人(理工科技+拔尖创新)\n二类含音乐舞蹈美术体育"},
  {name:"深圳外国语学校",district:"盐田区",type:"四大",color:"purple",score:568,
   desc:"以外语教学为特色，多个小语种课程。保送名校人数常年全省前列，国际化资源丰富。",
   tags:["外语特色","保送名额多","国际化","小语种"],
   recruit:"一类~100人(理工科技+人文社科+小语种)\n二类含体育艺术"},
  {name:"深圳高级中学(中心)",district:"福田区",type:"四大",color:"orange",score:568,
   desc:"市教育局直属重点高中，福田中心区。音乐舞蹈等艺术教育见长，理科实力也很强。",
   tags:["艺术突出","地理位置优","理科强","师资雄厚"],
   recruit:"一类~100人(理工科技+拔尖创新)\n二类含交响乐/舞蹈/体育"},
  // ===== 十大 =====
  {name:"红岭中学",district:"福田区",type:"十大",color:"",score:565,
   desc:"深圳规模最大的公办高中之一，校园优美。高考成绩稳步上升，理科竞赛成绩出色。",
   tags:["规模最大","高考进步快","理科竞赛","福田名校"],
   recruit:"一类~80人(理工科技+拔尖创新)\n二类含多种体育艺术"},
  {name:"宝安中学",district:"宝安区",type:"十大",color:"green",score:564,
   desc:"宝安区龙头学校，新增航空航天自招方向。理工科技见长，与多所高校有科创合作。",
   tags:["宝安龙头","航空航天","理工特色","高校合作"],
   recruit:"一类~70人(理工科技+航空航天+科创)\n二类含体育艺术"},
  {name:"育才中学",district:"南山区",type:"十大",color:"purple",score:564,
   desc:"南山区老牌名校，毗邻蛇口自贸区。以国际化视野和素质教育见长，高考成绩稳居前列，播音主持也有招生。",
   tags:["南山老牌名校","国际化视野","素质教育","播音主持"],
   recruit:"一类含理工科技+拔尖创新\n二类含播音主持+体育"},
  {name:"深大附中",district:"南山区",type:"十大",color:"orange",score:563,
   desc:"依托深圳大学资源办学，南山重点高中。学生可共享大学实验室，播音主持也有招生。",
   tags:["依托深大","大学资源","南山重点","播音主持"],
   recruit:"一类~60人(理工科技+科创)\n二类含播音主持"},
  {name:"南外高级中学",district:"南山区",type:"十大",color:"",score:561,
   desc:"南山外国语学校（集团）旗下高中，区直属重点。国际化氛围浓厚，英语教学突出。",
   tags:["南山直属","国际化","英语突出","集团化办学"],
   recruit:"一类含拔尖创新\n二类含体育艺术"},
  {name:"深圳科学高中",district:"龙岗区",type:"十大",color:"green",score:560,
   desc:"以科技创新为办学特色，深圳科创教育标杆。设有科创实验室、AI实验室等先进设施。科创AI专项30个名额！",
   tags:["科创品牌校","AI实验室","理工特色","创新教育"],
   recruit:"一类110人(科创AI 30+数学30+拔尖创新50)"},
  // ===== 前20 =====
  {name:"北师大南山附中",district:"南山区",type:"前20",color:"purple",score:561,
   desc:"北京师范大学合作办学，南山区重点高中。师资力量强，教学理念先进，理科见长。",
   tags:["北师大合办","师资雄厚","理科强","南山重点"],
   recruit:"一类含拔尖创新\n二类含体育艺术"},
  {name:"南山外国语学校",district:"南山区",type:"前20",color:"",score:556,
   desc:"南山区集团化办学标杆，外语教学特色明显。高考成绩稳步上升，走读线明显低于住宿线。",
   tags:["外语特色","集团标杆","进步快","走读优势"],
   recruit:"一类含拔尖创新\n二类含体育艺术"},
  {name:"深圳第二高级中学",district:"南山区",type:"前20",color:"green",score:556,
   desc:"市教育局直属高中，南山西丽片区。艺术教育特色，播音主持有招生名额，高考进步快。",
   tags:["市直属","艺术教育","播音主持","进步显著"],
   recruit:"一类含拔尖创新\n二类含播音主持+体育"},
  {name:"龙城高级中学",district:"龙岗区",type:"前20",color:"orange",score:555,
   desc:"龙岗区头部高中，教学质量稳定上升。兼顾学术与艺术，播音主持有招生。",
   tags:["龙岗头部","教学稳定","播音主持","艺术特色"],
   recruit:"一类~60人\n二类含播音主持+体育"},
  {name:"南科大附中",district:"南山区",type:"前20",color:"purple",score:554,
   desc:"依托南方科技大学资源办学，科创教育特色鲜明。学生可参与大学科研项目，理工科教学突出。",
   tags:["依托南科大","科创教育","理工突出","大学资源"],
   recruit:"一类含科创+理工科技\n二类含体育艺术"},
  {name:"翠园中学",district:"罗湖区",type:"前20",color:"",score:553,
   desc:"罗湖区头部学校，百年办学历史。高考成绩优异，近年进步显著。语言表演/朗诵有招生。",
   tags:["罗湖头部","百年历史","进步显著","语言表演"],
   recruit:"一类含拔尖创新\n二类含语言表演+体育"},
  {name:"深圳第二实验学校",district:"罗湖区",type:"前20",color:"green",score:553,
   desc:"市教育局直属传统名校，罗湖片区。教学实力强劲，播音主持有招生。",
   tags:["市直属","传统名校","播音主持","教学扎实"],
   recruit:"一类含拔尖创新\n二类含播音主持+体育"},
  {name:"深理工附中",district:"光明区",type:"前20",color:"orange",score:553,
   desc:"依托中国科学院深圳理工大学资源办学，光明科学城核心区。科创和理工科教育是最大亮点。",
   tags:["中科院背景","光明科学城","理工特色","科创优势"],
   recruit:"一类含理工科技+科创\n二类含体育"},
  {name:"龙华高级中学",district:"龙华区",type:"前20",color:"purple",score:551,
   desc:"龙华区头部学校，发展迅速。开设播音主持和戏剧表演项目。",
   tags:["龙华头部","发展迅速","戏剧表演","播音主持"],
   recruit:"一类含拔尖创新\n二类含播音主持+戏剧表演+体育"},
  {name:"人大附中深圳学校",district:"大鹏新区",type:"前20",color:"",score:550,
   desc:"中国人民大学附属中学合作办学，大鹏新区优质高中。名校基因+优美校园环境，理科教育突出。",
   tags:["人大附合办","名校基因","理科突出","大鹏明珠"],
   recruit:"一类含理工科技+拔尖创新\n二类含体育"},
  // ===== 二梯队 =====
  {name:"深实验光明高中",district:"光明区",type:"二梯队",color:"green",score:549,
   desc:"深圳实验学校集团光明校区，传承实验学校教育理念。光明科学城配套名校，近年热度持续攀升。",
   tags:["实验学校系","光明科学城","热度上升","品牌传承"],
   recruit:"一类含拔尖创新\n二类含体育艺术"},
  {name:"北大附深",district:"南山区",type:"二梯队",color:"orange",score:548,
   desc:"北京大学附属中学深圳分校，南山桃源片区。传承北大人文精神，学术氛围浓厚。",
   tags:["北大合办","人文精神","学术氛围","南山优质"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"深高级东校区",district:"坪山区",type:"二梯队",color:"purple",score:546,
   desc:"深圳高级中学坪山校区，四大品牌延伸。管理模式与中心校区一致，性价比较高。",
   tags:["四大分校","品牌延伸","性价比高","坪山优质"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"新安中学（集团）",district:"宝安区",type:"二梯队",color:"",score:543,
   desc:"宝安区重点高中，集团化办学。新增航空航天自招方向，播音主持也有招生。",
   tags:["宝安重点","航空航天","集团化","播音主持"],
   recruit:"一类含拔尖创新+航空航天\n二类含播音主持+体育"},
  {name:"华中师大龙岗附中",district:"龙岗区",type:"二梯队",color:"green",score:543,
   desc:"华中师范大学合作办学，龙岗区优质高中。师资实力强，教育理念先进。",
   tags:["华中师大合办","师资强","龙岗优质","教育理念先进"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"深中实验高中",district:"光明区",type:"二梯队",color:"orange",score:541,
   desc:"深圳中学高中园三校之一，传承深中教育理念。光明科学城新校区，设施一流。",
   tags:["深中高中园","设施一流","光明新校","深中传承"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"深圳第二外国语学校",district:"龙华区",type:"二梯队",color:"purple",score:540,
   desc:"市教育局直属，龙华片区。新增航空航天自招方向，外语教学也是特色之一。",
   tags:["市直属","航空航天","外语教学","龙华优质"],
   recruit:"一类含航空航天+科创\n二类含体育"},
  {name:"深中科技高中",district:"光明区",type:"二梯队",color:"",score:539,
   desc:"深圳中学高中园三校之一，以科技教育为核心。科创专项招生名额充足，理工科方向突出。",
   tags:["深中高中园","科技教育","科创专项","理工突出"],
   recruit:"一类80人(数学/物理/化学/科创/生物)"},
  {name:"深外龙华",district:"龙华区",type:"二梯队",color:"green",score:537,
   desc:"深圳外国语学校龙华校区，四大品牌延伸。外语教学特色传承，龙华区热度较高。",
   tags:["四大分校","外语传承","龙华热门","品牌延伸"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"深中数理高中",district:"光明区",type:"二梯队",color:"orange",score:536,
   desc:"深圳中学高中园三校之一，侧重数理基础学科。与深中教研体系接轨，适合数理突出的学生。",
   tags:["深中高中园","数理特色","基础学科","教研接轨"],
   recruit:"一类含拔尖创新\n二类含体育"},
  // ===== 三梯队 =====
  {name:"福田中学",district:"福田区",type:"三梯队",color:"purple",score:534,
   desc:"福田区老牌高中，地处中心城区。近年高考进步明显，走读线低于住宿线约4分。",
   tags:["福田老牌","中心城区","进步明显","走读优势"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"明德实验学校",district:"福田区",type:"三梯队",color:"",score:533,
   desc:"福田区创新体制学校，腾讯公益基金会协办。小班教学，课程体系丰富，走读线较低。",
   tags:["创新体制","腾讯协办","小班教学","课程丰富"],
   recruit:"一类含拔尖创新\n二类含体育艺术"},
  {name:"南头中学",district:"南山区",type:"三梯队",color:"green",score:532,
   desc:"南山区历史最悠久的高中之一，地处南头古城片区。教学稳定，走读线有优势。",
   tags:["历史悠久","南山老校","教学稳定","走读优势"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"华南师大附中海岸城分校",district:"南山区",type:"三梯队",color:"orange",score:531,
   desc:"华南师范大学附属中学深圳分校，南山后海片区。依托华师资源，教学理念先进。",
   tags:["华师合办","后海片区","资源优质","理念先进"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"盐田高级中学",district:"盐田区",type:"三梯队",color:"purple",score:530,
   desc:"盐田区唯一公办高中，校园环境优美。近年引进名校管理团队，高考成绩上升。",
   tags:["盐田唯一","环境优美","管理提升","进步明显"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"罗湖外语学校",district:"罗湖区",type:"三梯队",color:"",score:529,
   desc:"罗湖区外语特色高中，英语教学是王牌。走读线低于住宿线约4分，适合罗湖走读生。",
   tags:["外语特色","英语王牌","走读优势","罗湖片区"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"罗湖高级中学",district:"罗湖区",type:"三梯队",color:"green",score:528,
   desc:"罗湖区优质高中，近年高考成绩进步。校园设施完善，体育教育特色。",
   tags:["罗湖优质","进步显著","设施完善","体育特色"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"致理中学",district:"宝安区",type:"三梯队",color:"orange",score:527,
   desc:"宝安区新建优质高中，航空航天自招方向。硬件设施先进，发展势头强劲。",
   tags:["宝安新建","航空航天","设施先进","发展迅猛"],
   recruit:"一类含航空航天+拔尖创新\n二类含体育"},
  {name:"西乡中学",district:"宝安区",type:"三梯队",color:"purple",score:527,
   desc:"宝安区老牌高中，地处西乡片区。教学扎实，体育传统校。",
   tags:["宝安老牌","教学扎实","体育传统","西乡片区"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"第三高级中学",district:"龙岗区",type:"特色校",color:"",score:525,
   desc:"深圳艺术教育品牌学校，播音主持和戏剧表演闻名。设有出国留学班。播音+表演共12人名额是公办校中最多的。",
   tags:["艺术品牌校","播音主持王牌","戏剧表演","出国班"],
   recruit:"二类: 播音6人+戏剧表演6人+声乐+器乐+美术+舞蹈+体育"},
  {name:"梅林中学",district:"福田区",type:"三梯队",color:"green",score:524,
   desc:"福田区梅林片区，教学质量稳定。走读线低于住宿线约4分，适合福田北部走读生。",
   tags:["梅林片区","教学稳定","走读优势","福田北部"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"光明中学",district:"光明区",type:"三梯队",color:"orange",score:523,
   desc:"光明区优质高中，播音主持有招生。近年随光明科学城发展，学校热度上升。",
   tags:["光明优质","播音主持","热度上升","科学城配套"],
   recruit:"一类含拔尖创新\n二类含播音主持+体育"},
  {name:"光明高级中学",district:"光明区",type:"三梯队",color:"purple",score:522,
   desc:"光明区重点高中之一，校园环境好。教学管理规范，适合光明片区学生。",
   tags:["光明重点","环境优美","管理规范","本地优质"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"平冈中学",district:"龙岗区",type:"三梯队",color:"",score:521,
   desc:"龙岗区老牌高中，地处龙岗中心城。教学底蕴深厚，体育教育传统强。",
   tags:["龙岗老牌","底蕴深厚","体育传统","中心城区"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"龙岗区外国语学校",district:"龙岗区",type:"三梯队",color:"green",score:520,
   desc:"龙岗区外语特色高中，英语教学突出。近年发展迅速，适合有外语特长的学生。",
   tags:["龙岗外语","英语突出","发展迅速","特色鲜明"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"观澜中学",district:"龙华区",type:"三梯队",color:"orange",score:519,
   desc:"龙华区观澜片区高中，教学稳定。校园面积较大，体育设施完善。",
   tags:["龙华观澜","教学稳定","校园宽敞","体育设施好"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"布吉中学",district:"龙岗区",type:"三梯队",color:"purple",score:518,
   desc:"龙岗区布吉片区，地理位置便利靠近罗湖。教学扎实，适合龙岗南部学生。",
   tags:["布吉片区","交通便利","教学扎实","龙岗南部"],
   recruit:"一类含拔尖创新\n二类含体育"},
  // ===== 四梯队 =====
  {name:"龙华中学",district:"龙华区",type:"四梯队",color:"",score:517,
   desc:"龙华区中心片区老校，教学经验丰富。校园正在升级改造中。",
   tags:["龙华中心","教学经验丰富","老校升级","本地稳定"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"平湖外国语学校",district:"龙岗区",type:"四梯队",color:"green",score:516,
   desc:"龙岗区平湖片区外语特色高中，靠近东莞。英语教学特色，适合平湖凤岗片区学生。",
   tags:["平湖片区","外语特色","跨区便利","英语教学"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"坪山高级中学",district:"坪山区",type:"四梯队",color:"orange",score:515,
   desc:"坪山区重点高中，播音主持有招生。坪山新区快速发展，学校硬件持续升级。",
   tags:["坪山重点","播音主持","硬件升级","发展区域"],
   recruit:"一类含拔尖创新\n二类含播音主持+体育"},
  {name:"横岗高级中学",district:"龙岗区",type:"四梯队",color:"purple",score:514,
   desc:"龙岗区横岗片区，近年引进优秀师资。教学改革力度大，进步势头明显。",
   tags:["横岗片区","师资引进","教改力度大","进步明显"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"沙井中学",district:"宝安区",type:"四梯队",color:"",score:512,
   desc:"宝安区沙井片区老牌高中，教学经验丰富。校园环境优美，适合沙井松岗片区学生。",
   tags:["沙井片区","老牌高中","环境优美","本地优质"],
   recruit:"一类含拔尖创新\n二类含体育"},
  {name:"松岗中学",district:"宝安区",type:"四梯队",color:"green",score:501,
   desc:"宝安区松岗片区高中，播音主持有招生。入门控制线较低，性价比较高。",
   tags:["松岗片区","播音主持","性价比高","入门友好"],
   recruit:"一类含拔尖创新\n二类含播音主持+体育"},
  // ===== 特色校 =====
  {name:"深圳市美术学校",district:"罗湖区",type:"特色校",color:"purple",score:459,
   desc:"深圳唯一公办艺术高中，美术教育为核心，同时开设播音主持和影视表演。控制线全市最低(380分)。",
   tags:["唯一公办艺术高中","播音表演","美术特色","控制线最低"],
   recruit:"二类: 美术+播音主持+影视表演+舞蹈+音乐+书法等"}
];

// ==================== 中考相关网站数据 ====================
const websiteData = {
  official: [
    {name:"深圳市教育局",url:"https://szeb.sz.gov.cn/",desc:"深圳教育最高行政主管部门官网，发布中考招生政策文件、通知公告、自主招生计划等最权威信息",tags:["政策发布","招生通知","最权威"],icon:"🏛️",priority:"必看",rss:"",updateFreq:"政策发布时更新"},
    {name:"深圳市招生考试办公室",url:"https://szeb.sz.gov.cn/szzkw/",desc:"深圳招考办官网，负责中考、高考、自考等各类考试的组织与管理，发布考试安排、成绩查询等",tags:["考试安排","成绩查询","招考日历"],icon:"📋",priority:"必看",rss:"",updateFreq:"考试节点前密集更新"},
    {name:"招考办 · 中考信息公告",url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html",desc:"招考办中考信息专栏，集中发布中考报名、志愿填报、录取通知等最新动态",tags:["报名通知","志愿填报","录取公告"],icon:"📢",priority:"必看",rss:"",updateFreq:"中考季密集更新"},
    {name:"高中阶段学校报名体系建设",url:"https://szeb.sz.gov.cn/szzkw/ztzl/gzjdxxbxtsjs/",desc:"高中阶段招生体系建设专题页面，含各高中简介、招生计划、学校对比等",tags:["学校简介","招生计划","体系建设"],icon:"🏫",priority:"必看",rss:"",updateFreq:"年度更新"},
    {name:"深圳市中考中招管理系统",url:"https://www.szzk.edu.cn/",desc:"中考报名、志愿填报、成绩查询、录取查询的核心操作系统，考生必登录平台",tags:["在线报名","志愿填报","成绩查询","录取查询"],icon:"💻",priority:"必用",rss:"",updateFreq:"报名/填报/查询开放期间"},
    {name:"自主招生报名系统",url:"https://www.szzk.edu.cn/zzzs",desc:"一类自主招生在线报名入口，考生通过此系统填报自主招生志愿",tags:["自招报名","一类自招","在线填报"],icon:"📝",priority:"必用",rss:"",updateFreq:"自招报名期间开放"},
    {name:"2025年中考政策及网上宣传",url:"https://szeb.sz.gov.cn/szszsksbgs/zkcx/zkzz/szs2025nzkzcjwsxc/index.html",desc:"2025年中考政策专题页面，包含志愿填报平台、高中学校宣传、通知公告等",tags:["志愿填报","学校宣传","政策汇总"],icon:"📑",priority:"重要",rss:"",updateFreq:"年度专题"},
    {name:"广东省教育考试院",url:"https://eea.gd.gov.cn/",desc:"广东省级教育考试主管部门，发布全省统一的中考政策、考试标准等上位政策",tags:["省级政策","考试标准","全省统一"],icon:"🏢",priority:"参考",rss:"",updateFreq:"政策发布时更新"},
    {name:"深圳市教育公共服务平台",url:"https://sz.edu.cn/",desc:"深圳智慧教育综合服务平台，提供教育资源、学校信息、教育政策等综合服务",tags:["综合服务","教育资源","学校信息"],icon:"🎓",priority:"参考",rss:"",updateFreq:"持续更新"}
  ],
  schools: [
    {name:"深圳中学官网",url:"https://www.shenzhong.net/",icon:"🏆",desc:"深圳中学官方网站，自招简章和学校动态",district:"罗湖区"},
    {name:"深圳中学高中园",url:"https://www.szzxgzy.net/",icon:"🏫",desc:"深中高中园(实验/科技/数理)三校自招信息",district:"光明区"},
    {name:"深圳实验学校",url:"https://szsy.cn/",icon:"🌟",desc:"深圳实验学校官网，招生公告和学校动态",district:"福田区"},
    {name:"深圳外国语学校",url:"https://www.sfls.net.cn/",icon:"🌍",desc:"深外官网，自招、小语种招生信息",district:"盐田区"},
    {name:"深圳高级中学",url:"https://www.cn-school.com/",icon:"🎵",desc:"深高级官网，含艺术类招生信息",district:"福田区"},
    {name:"红岭中学",url:"https://hlzx.szftedu.cn/",icon:"🔴",desc:"红岭中学官网，招生动态",district:"福田区"},
    {name:"深圳科学高中",url:"https://www.szskgz.com/",icon:"🔬",desc:"科学高中官网，科创AI招生详情",district:"龙岗区"}
  ],
  thirdParty: [
    {name:"深圳本地宝 · 中考专题",url:"https://sz.bendibao.com/edu/zhuantizhongkao/",desc:"本地宝中考专题，整合分数线、报名时间、志愿填报、录取查询等全流程信息，解读清晰易懂",tags:["分数线","志愿填报","政策解读"],icon:"📚",priority:"推荐",updateFreq:"持续跟进更新"},
    {name:"本地宝 · 志愿填报辅助系统",url:"https://m.bendibao.com/mtools/zhongkaopingfen/",desc:"根据模拟分数智能推荐学校，按冲稳保策略辅助志愿填报",tags:["分数定位","志愿辅助","智能推荐"],icon:"🎯",priority:"推荐",updateFreq:"志愿填报期间"},
    {name:"深圳中考网 (szzk.cn)",url:"https://www.szzk.cn/",desc:"深圳中考信息汇总平台，包含各学校详细介绍、分数线、招生信息等",tags:["学校详情","分数线","信息汇总"],icon:"📊",priority:"推荐",updateFreq:"持续更新"},
    {name:"知乎 · 深圳中考话题",url:"https://www.zhihu.com/topic/20078498",desc:"家长和考生的真实经验分享，备考攻略、选校建议、自招经验贴",tags:["经验分享","选校建议","备考攻略"],icon:"💬",priority:"辅助",updateFreq:"社区持续讨论"},
    {name:"腾讯新闻 · 深圳中考",url:"https://new.qq.com/search?query=深圳中考",desc:"深圳中考最新新闻资讯，包括政策变化、分数线分析、学校动态等",tags:["新闻资讯","政策变化","实时动态"],icon:"📰",priority:"辅助",updateFreq:"实时"}
  ]
};

// ==================== 信息更新时间线 ====================
const updateTimeline = [
  {month:"3月", events:[
    {date:"3月中旬", title:"中考招生政策发布", desc:"教育局发布当年中考招生通知", source:"深圳市教育局", url:"https://szeb.sz.gov.cn/", important:true},
    {date:"3月下旬", title:"中考报名开始", desc:"考生在学校集体办理报名手续", source:"中考中招系统", url:"https://www.szzk.edu.cn/", important:true}
  ]},
  {month:"4月", events:[
    {date:"4月", title:"自主招生计划公布", desc:"教育局发布各高中自主招生计划表", source:"深圳市教育局", url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html", important:true},
    {date:"4月", title:"体育中考", desc:"体育科目考试", source:"招考办", url:"https://szeb.sz.gov.cn/szzkw/", important:false}
  ]},
  {month:"5月", events:[
    {date:"5月中旬", title:"各校自招简章发布", desc:"各高中发布详细自招简章和报名要求", source:"各学校官网", url:"", important:true},
    {date:"5月下旬", title:"志愿填报开始", desc:"网上填报中考志愿（约2周时间）", source:"中考中招系统", url:"https://www.szzk.edu.cn/", important:true}
  ]},
  {month:"6月", events:[
    {date:"6月上旬", title:"一类自招报名", desc:"线上报名一类自主招生（约5天）", source:"自招报名系统", url:"https://www.szzk.edu.cn/zzzs", important:true},
    {date:"6月中旬", title:"二类自招报名", desc:"到学校现场报名二类自主招生", source:"各学校", url:"", important:false},
    {date:"6月下旬", title:"中考考试", desc:"初中学业水平考试（约2-3天）", source:"招考办", url:"https://szeb.sz.gov.cn/szzkw/", important:true}
  ]},
  {month:"7月", events:[
    {date:"7月上旬", title:"自招专项考核", desc:"一类自招统一考核日（7月5日前后）", source:"各学校", url:"", important:true},
    {date:"7月上旬", title:"自招结果公示", desc:"自招拟录名单公示（约5天）", source:"招考办", url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html", important:true},
    {date:"7月中旬", title:"成绩公布", desc:"中考成绩和各批次分数线公布", source:"中考中招系统", url:"https://www.szzk.edu.cn/", important:true},
    {date:"7月下旬", title:"分批录取", desc:"按批次进行录取（约1-2周）", source:"招考办", url:"https://szeb.sz.gov.cn/szzkw/", important:true}
  ]},
  {month:"8月", events:[
    {date:"8月上旬", title:"补录/补报志愿", desc:"部分未满额学校进行补录", source:"中考中招系统", url:"https://www.szzk.edu.cn/", important:false},
    {date:"8月中旬", title:"录取通知书发放", desc:"各高中发放录取通知书", source:"各学校", url:"", important:false}
  ]}
];

// ==================== 数据更新状态 ====================
const dataUpdateStatus = {
  lastUpdate: "2025-07-28",
  version: "v3.0",
  sources: [
    {name:"公办高中分数线(92所)", status:"已更新", date:"2025-07-27", source:"深圳招考办"},
    {name:"民办高中分数线(47所)", status:"已更新", date:"2025-07-27", source:"深圳招考办"},
    {name:"中职技校分数线", status:"已更新", date:"2025-07-28", source:"深圳招考办"},
    {name:"自主招生计划", status:"已更新", date:"2025-05-26", source:"深圳市教育局"},
    {name:"各校自招简章", status:"已更新", date:"2025-06-10", source:"各学校官网"},
    {name:"科创类名额", status:"已更新", date:"2025-06-10", source:"招考办公告"},
    {name:"播音表演类", status:"已更新", date:"2025-06-10", source:"各学校简章"},
    {name:"民办高中学费", status:"已更新", date:"2025-08-25", source:"各学校官方公示"}
  ],
  nextCheck: [
    {event:"2026年中考政策", expectedTime:"2026年3月", checkUrl:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html"},
    {event:"2026年自招计划", expectedTime:"2026年4-5月", checkUrl:"https://szeb.sz.gov.cn/"},
    {event:"2026年分数线", expectedTime:"2026年7月", checkUrl:"https://www.szzk.edu.cn/"},
    {event:"2026年各校简章", expectedTime:"2026年5-6月", checkUrl:"各学校官网"}
  ]
};

// ==================== 填报指南数据 ====================
const guideData = {
  // 官方权威资源
  official: [
    {name:"2025年考生报考指导手册",url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/content/post_12188593.html",
     desc:"深圳市招考办官方发布的报考指导手册，涵盖中考政策解读、志愿填报规则、录取批次说明、各高中招生计划等全面内容。每年更新，是最权威的填报参考资料。",
     tags:["官方发布","最权威","必读"],icon:"📖",type:"文档",source:"深圳市招考办",priority:"必读"},
    {name:"2025年中考政策及网上宣传专题",url:"https://szeb.sz.gov.cn/szszsksbgs/zkcx/zkzz/szs2025nzkzcjwsxc/index.html",
     desc:"招考办年度中考政策专题页面，包含志愿填报平台入口、高中学校宣传视频和材料、通知公告等，一站式获取官方信息。",
     tags:["年度专题","一站式","学校宣传"],icon:"📑",type:"专题",source:"深圳市招考办",priority:"必读"},
    {name:"深圳中考志愿填报系统",url:"https://www.szzk.edu.cn/",
     desc:"中考志愿网上填报的唯一官方入口。5月下旬至6月初开放，考生通过此系统完成志愿填报、确认和打印。",
     tags:["官方入口","在线填报","唯一渠道"],icon:"💻",type:"系统",source:"深圳中招系统",priority:"必用"},
    {name:"深圳市教育局中考招生政策文件汇编",url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html",
     desc:"中考信息公告专栏，集中发布每年中考报名通知、招生计划、录取标准、自主招生方案等所有政策文件原文。",
     tags:["政策原文","文件汇编","招生通知"],icon:"📋",type:"政策",source:"深圳市教育局",priority:"必读"},
    {name:"指标生名额分配表",url:"https://szeb.sz.gov.cn/szzkw/zkgg/zkxx/index.html",
     desc:"指标生是中考「低分进名校」的重要途径。每年教育局会公布各初中学校分配到各高中的指标生名额表，填报志愿前务必查看自己学校的指标分配情况。",
     tags:["指标生","名额分配","低分进名校"],icon:"📊",type:"数据",source:"深圳市教育局",priority:"重要"}
  ],
  // 视频攻略
  videos: [
    {name:"深圳中考志愿填报全攻略（2025版）",url:"https://www.douyin.com/search/2025%E6%B7%B1%E5%9C%B3%E4%B8%AD%E8%80%83%E5%BF%97%E6%84%BF%E5%A1%AB%E6%8A%A5%E6%94%BB%E7%95%A5",
     desc:"抖音上大量深圳本地升学博主录制的中考志愿填报攻略视频，涵盖冲稳保策略、指标生填报技巧、各批次规则讲解等，实操性强，适合视觉学习者。",
     tags:["视频攻略","冲稳保策略","填报实操"],icon:"🎬",platform:"抖音",source:"深圳升学博主"},
    {name:"一个视频教会你深圳中考志愿填报",url:"https://www.douyin.com/video/7488261235314609467",
     desc:"深圳升学家长帮出品的志愿填报视频教程——又稳又准又狠的填报策略，手把手教你8个志愿如何排列组合。近5000点赞的热门视频。",
     tags:["热门视频","手把手","策略讲解"],icon:"🎥",platform:"抖音",source:"深圳升学家长帮"},
    {name:"B站深圳中考志愿填报合集",url:"https://search.bilibili.com/all?keyword=%E6%B7%B1%E5%9C%B3%E4%B8%AD%E8%80%83%E5%BF%97%E6%84%BF%E5%A1%AB%E6%8A%A5",
     desc:"B站上专业升学老师的详细志愿填报教程，时长较长（30分钟~1小时），涵盖系统操作演示、数据分析、策略推演等深度内容。",
     tags:["深度讲解","系统演示","数据分析"],icon:"📺",platform:"B站",source:"升学教育UP主"},
    {name:"各高中学校官方宣传视频",url:"https://szeb.sz.gov.cn/szszsksbgs/zkcx/zkzz/szs2025nzkzcjwsxc/index.html",
     desc:"招考办年度中考宣传专题中，各高中学校上传的官方招生宣传视频，展示校园环境、办学特色、师资力量、学生活动等，直观了解学校。",
     tags:["学校宣传","校园环境","官方视频"],icon:"🏫",platform:"官方专题",source:"各高中学校"}
  ],
  // 填报工具
  tools: [
    {name:"本地宝 · 志愿填报辅助系统",url:"https://m.bendibao.com/mtools/zhongkaopingfen/",
     desc:"输入模考成绩或预估分数，系统自动推荐可冲刺、稳妥和保底学校，按「冲稳保」策略辅助志愿排列。是填报志愿前的必用模拟工具。",
     tags:["分数定位","冲稳保","智能推荐"],icon:"🎯",type:"在线工具",source:"深圳本地宝"},
    {name:"深圳中考网 · 学校对比",url:"https://www.szzk.cn/",
     desc:"提供各学校详细信息对比功能，包括历年分数线走势、招生计划变化、学校特色等，帮助缩小选校范围。",
     tags:["学校对比","分数线走势","信息汇总"],icon:"📊",type:"信息平台",source:"深圳中考网"},
    {name:"本地宝 · 录取分数线查询",url:"https://sz.bendibao.com/edu/2022726/895410.shtm",
     desc:"深圳2023-2025年各公办/民办高中录取分数线汇总表，方便对比历年分数线变化趋势，预判来年走向。",
     tags:["历年数据","趋势对比","分数线"],icon:"📈",type:"数据查询",source:"深圳本地宝"}
  ],
  // 经验文章
  articles: [
    {name:"2025深圳中考志愿填报技巧与注意事项",url:"https://sz.bendibao.com/edu/2025516/987882.shtm",
     desc:"本地宝编辑整理的志愿填报技巧大全，涵盖8个志愿如何排列、冲稳保比例、指标生策略、走读/住宿选择、各批次注意事项等实用内容。",
     tags:["填报技巧","注意事项","实用指南"],icon:"📝",source:"深圳本地宝"},
    {name:"深圳2025年中考志愿填报全攻略（知乎）",url:"https://zhuanlan.zhihu.com/p/31117347107",
     desc:"知乎高赞中考志愿填报攻略文章，从政策解读到填报策略，覆盖录取规则、批次设置、注意事项、常见误区等，评论区有大量家长讨论。",
     tags:["高赞文章","策略分析","家长讨论"],icon:"💬",source:"知乎"},
    {name:"深圳中考报考手册解读（2025版）",url:"https://zhuanlan.zhihu.com/p/1908905059187654986",
     desc:"对官方报考手册的详细解读，配合操作截图说明网上志愿填报流程，图文并茂，适合第一次填报的家长。",
     tags:["手册解读","操作图解","新手友好"],icon:"📘",source:"知乎"},
    {name:"搜狐 · 2025志愿填报准备及选择指南",url:"https://www.sohu.com/a/872469591_121956424",
     desc:"从家长和学生双视角出发的志愿填报指南，分析了分数优先、遵循志愿顺序的核心原则，并给出不同分数段的选校建议。",
     tags:["选校建议","分数分析","双视角"],icon:"📰",source:"搜狐教育"},
    {name:"知乎 · 深圳中考话题讨论",url:"https://www.zhihu.com/topic/20078498",
     desc:"知乎深圳中考话题圈，有大量过来人的真实经验分享、备考攻略、选校踩坑记录等。评论区互动活跃，可以直接提问。",
     tags:["经验分享","过来人","互动讨论"],icon:"🗣️",source:"知乎社区"}
  ],
  // 核心填报技巧
  tips: [
    {title:"🎯 「冲稳保」策略",content:"8个志愿建议按2:3:3或3:3:2比例排列——前2-3个冲高（分数略高于自己的学校），中间3个稳妥（与自己分数匹配），最后2-3个保底（确保能录取）。"},
    {title:"📊 指标生优先用",content:"指标生是低分进名校的重要途径。优先在指标生志愿中填报目标学校，如果分数差10分以内，指标生机会很大。注意查看自己学校分到各高中的指标名额。"},
    {title:"🏠 走读/住宿要想清楚",content:"2025年首次实行走读/住宿分线录取。走读线通常低3-5分，但需要家住学校附近。如果只勾选住宿，录取分会更高。建议「住宿+走读」都勾选以增加录取机会。"},
    {title:"⚠️ 录取后不能退档",content:"中考志愿一旦被录取，不能退档、不能补填。所以每一个志愿都要是你愿意去的学校，不要随意「浪费」保底志愿。"},
    {title:"🔄 参考历年分数线",content:"分数线每年有波动，建议参考近3年数据。关注排名比关注绝对分数更重要——看自己在全市的排名位次，对应历年同位次能进哪所学校。"},
    {title:"📋 自主招生和统招志愿是独立的",content:"自主招生在「自招批」录取，不影响后面的统招志愿。如果自招没被录取，统招志愿正常进行。所以符合条件的同学一定要报自招，多一次机会。"}
  ]
};
